# This is a basic workflow to help you get started with Actions

name: Run R Script hourly

# Controls when the workflow will run
on:
  schedule: 
    - cron: '0 * * * *' #runs every hour at mint 0
    
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

        
      - name : Install R packages
        run: Rscript -e 'install.packages(c("plotly", "lubridate", "akima", "stringr", "tidyr", "dplyr"))'
        
      # Runs a set of commands using the runners shell
      - name: Run R script
        run: Rscript -e "rmarkdown::render('3d_heatmap_with_gtihub.Rmd')"


      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"


      - name: Create timestamped branch and push
        run: |
          TIMESTAMP=$(date -u +"run-%Y-%m-%d-%H-%M")
          git checkout -b $TIMESTAMP
          git add .
          git commit -m "Automated run at $TIMESTAMP"
          git push origin $TIMESTAMP

      
