name: Build and Render R Heatmap

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R_LIBS_USER: /home/runner/work/_temp/Library
      TZ: UTC
      _R_CHECK_SYSTEM_CLOCK_: FALSE
      NOT_CRAN: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 3.1.11

      - name: Install plotly and dependencies
        run: |
          Rscript -e "
            .libPaths(Sys.getenv('R_LIBS_USER'));
            install.packages(c(
              'plotly', 'htmlwidgets', 'crosstalk', 'ggplot2',
              'httr', 'jsonlite', 'curl'
            ), repos='https://cloud.r-project.org')
          "

      - name: Install other required R packages
        run: |
          Rscript -e "
            .libPaths(Sys.getenv('R_LIBS_USER'));
            install.packages(c(
              'rmarkdown', 'lubridate', 'akima', 'stringr',
              'tidyr', 'dplyr'
            ), repos='https://cloud.r-project.org')
          "


      - name: Render R Markdown
        run: |
          Rscript -e "
            .libPaths(Sys.getenv('R_LIBS_USER'));
            rmarkdown::render('3d_heatmap_with_gtihub.Rmd')
          "
